/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Rolando
 */
public class Ventana1 extends javax.swing.JFrame {
    
    public static String text = "";
    

    /**
     * Creates new form Ventana1
     */
    public Ventana1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Add = new javax.swing.JLabel();
        jFileChooser2 = new javax.swing.JFileChooser();
        Analyze = new javax.swing.JLabel();
        OK = new javax.swing.JButton();
        Search_inves = new javax.swing.JLabel();
        Keywords1 = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Author1 = new javax.swing.JButton();
        dropdown_list = new javax.swing.JComboBox<>();
        Choose_inves = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Add.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        Add.setText("Agrega tu resumen");
        jPanel1.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 11, 180, 20));

        jFileChooser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser2ActionPerformed(evt);
            }
        });
        jPanel1.add(jFileChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 11, -1, -1));

        Analyze.setBackground(new java.awt.Color(255, 255, 255));
        Analyze.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        Analyze.setText("Analizar resumen");
        jPanel1.add(Analyze, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 474, 170, 20));
        Analyze.getAccessibleContext().setAccessibleDescription("");

        OK.setText("OK");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        jPanel1.add(OK, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 553, -1, -1));

        Search_inves.setBackground(new java.awt.Color(255, 255, 255));
        Search_inves.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        Search_inves.setText("Buscar investigación por:");
        jPanel1.add(Search_inves, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 474, 240, 20));

        Keywords1.setText("Palabras Clave");
        Keywords1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Keywords1ActionPerformed(evt);
            }
        });
        jPanel1.add(Keywords1, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 512, -1, -1));

        Exit.setText("Salir");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 618, -1, -1));

        Author1.setText("Autor");
        jPanel1.add(Author1, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 553, -1, -1));

        dropdown_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "Y", "Z", "W" }));
        dropdown_list.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dropdown_listItemStateChanged(evt);
            }
        });
        dropdown_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdown_listActionPerformed(evt);
            }
        });
        jPanel1.add(dropdown_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 554, 220, -1));

        Choose_inves.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        Choose_inves.setText("Escoge una de las investigaciones");
        jPanel1.add(Choose_inves, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 525, 190, 20));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 920, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 440, 26, 220));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dropdown_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdown_listActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdown_listActionPerformed

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OKActionPerformed

    private void dropdown_listItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dropdown_listItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdown_listItemStateChanged

    private void Keywords1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Keywords1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Keywords1ActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_ExitActionPerformed

    private void jFileChooser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser2ActionPerformed
        // TODO add your handling code here:
        String aux = "";
        
        try {
//            Llamamos al método que permite cargar la ventana
      
//            Abrimos el archivo seleccionado
            File open = jFileChooser2.getSelectedFile();
            
//            Recorremos el archivo, leemos y lo plasmamos en un area de texto
            if (open != null) {
                
                FileReader archivos = new FileReader(open);
                BufferedReader read = new BufferedReader(archivos);
                while ((aux = read.readLine()) != null) {
                    
                    text += aux + "\n";   
                }
                read.close(); 
                
                System.out.println(text);
            }
        } catch (IOException e) {
            
            JOptionPane.showMessageDialog(null, e + "" +
           "\nNo se ha encontrado el archivo",
                 "ADVERTENCIA!!!",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jFileChooser2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add;
    private javax.swing.JLabel Analyze;
    private javax.swing.JButton Author1;
    private javax.swing.JLabel Choose_inves;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Keywords1;
    private javax.swing.JButton OK;
    private javax.swing.JLabel Search_inves;
    private javax.swing.JComboBox<String> dropdown_list;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
