/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author Rolando
 */
public class VentanaKeywords extends javax.swing.JFrame {

    /**
     * Creates new form VentanaKeywords
     */
    public VentanaKeywords() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Search_author = new javax.swing.JLabel();
        Search_author1 = new javax.swing.JLabel();
        Author = new javax.swing.JTextField();
        OK_author = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Search_author.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        Search_author.setText("Búsqueda de Investigaciones");
        getContentPane().add(Search_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 16, 279, 20));

        Search_author1.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        Search_author1.setText("por palabras clave");
        getContentPane().add(Search_author1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 42, -1, -1));

        Author.setText("Ingrese una palabra clave");
        Author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthorActionPerformed(evt);
            }
        });
        getContentPane().add(Author, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 117, 157, -1));

        OK_author.setText("OK");
        getContentPane().add(OK_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 143, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AuthorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaKeywords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaKeywords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaKeywords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaKeywords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaKeywords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Author;
    private javax.swing.JButton OK_author;
    private javax.swing.JLabel Search_author;
    private javax.swing.JLabel Search_author1;
    // End of variables declaration//GEN-END:variables
}
